### ISSUE TITLE
add rpc support

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/async.vim#13]
I have been thinking of having rpc support for quite sometime. This would be provided by `rpc.vim` which depends on `job.vim`. It could then use stdin/stdout to communicate with the servers.

**Comment by jalcine** [comment]
So this would involve another plugin as a (optional) dependency to this one? Sounds interesting.

**Comment by prabirshrestha** [comment]
No plans to support it because most of them can be done by [LSP](https://microsoft.github.io/language-server-protocol/) Other plugins can support it if needed.
