### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by nfischer** [prabirshrestha/async.vim#2]
This seems like a really promising vim library. I'd like to see more projects migrating to rely on this, if it's robust enough. I'd love to be able to move the `if has('nvim')` clauses out of my vimrc.

That being said, are you planning on adding unit tests? I don't have much time on my hands, but I may be able to help out if you can get something started. I'm not sure if you have a favorite vim testing framework yet, but I have some experience using [vroom](https://github.com/google/vroom).

**Comment by prabirshrestha** [comment]
Would love too but I'm not a viml expert. So feel free to send a PR.

**Comment by wsdjeg** [comment]
@prabirshrestha you can checkout the SpaceVim's job api test in 
https://github.com/SpaceVim/SpaceVim/blob/job/test/api/job.vader

BTW  I have implement fallback to sync system() feature in https://github.com/SpaceVim/SpaceVim/pull/460
