### ISSUE TITLE
Stepping buffer size is smaller

### ISSUE THREAD

**Issue by mattn** [prabirshrestha/async.vim#23]
Current implementation use 1024. This is smaller.

https://github.com/vim/vim/pull/3782

I send pull-request to vim/vim to make large size for Windows named pipe. When this pr is merged, we can change this size to 8192.

**Comment by prabirshrestha** [comment]
Is this even valid now given that we send the full text and let vim manage the buffering?

**Comment by mattn** [comment]
Yes, so closing
