### ISSUE TITLE
How do I use this plugin from another plugin?

### ISSUE THREAD

**Issue by vimark1** [prabirshrestha/async.vim#40]
I am trying to re-write this logic
https://github.com/heavenshell/vim-jsdoc/compare/master...vimark1:patch-1?expand=1#diff-db0abe5fcd735715e60b30d8975cfa00

ie. is there an equivalent to `package.json` in vim development? I am new to this :smile:

**Comment by prabirshrestha** [comment]
Install async.vim. Then follow instructions at https://github.com/prabirshrestha/async.vim#embedding and then remove async.vim plug in to test it works.
