### ISSUE TITLE
Cursor flickers 2 times after async job completes

### ISSUE THREAD

**Issue by poetaman** [prabirshrestha/async.vim#45]
Is it possible to not make cursor flicker when async job completes?

```
NVIM v0.6.0-dev+nightly-481-g6f48c018b
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by Shougo** [comment]
I think the example should be uploaded.

**Comment by poetaman** [comment]
@Shougo My bad, I had a couple of ``call system()`` in the handler callback of the job. Getting rid of those fixed it.

**Comment by Shougo** [comment]
Oh.
