### ISSUE TITLE
distribute as a package

### ISSUE THREAD

**Issue by coot** [prabirshrestha/async.vim#8]
It would be useful to switch to a package layout, i.e. put the `async.vim` inside
`start/async/autoload/async.vim`
Then the user would put it under `pack/async`. Check `:h package-create`. I checked that this works in vim-8 and nvim-0.2.0. 

This would also solve https://github.com/FrigoEU/psc-ide-vim/issues/61

**Comment by prabirshrestha** [comment]
Isn't this going to break other plugin managers? I haven't seen any other vim plugins include start.

Why not just use if you are planning to do it manually.

```vim
mkdir ~/.vim/pack/async.vim
cd ~/.vim/pack/async.vim
git clone https://github.com/prabirshrestha/async.vim.git start
```

**Comment by coot** [comment]
I am not sure, just posted a question on [vim_use](https://groups.google.com/forum/#!topic/vim_use/L3rGXTnxi8Y).

**Comment by coot** [comment]
Seems that the support across vim managers is not there yet, so closing this issue for now.
